In [54]:
import pandas as pd
from nltk.corpus import stopwords
import nltk

In [2]:
datos = "documentos_udea_2004_2024.xlsx"
df = pd.read_excel(datos)
df.head(10)

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
0,ACTAS,0198,2004/12/14,NaN,NaN,NaN,NaN
1,ACTAS,0283,2004/12/09,NaN,NaN,NaN,NaN
2,ACTAS,0282,2004/12/02,NaN,NaN,NaN,NaN
3,ACTAS,0280,2004/11/18,NaN,NaN,NaN,NaN
4,ACTAS,0279,2004/11/11,NaN,NaN,NaN,NaN
5,ACTAS,0197,2004/11/09,NaN,NaN,NaN,NaN
6,ACTAS,0278,2004/11/04,NaN,NaN,NaN,NaN
7,ACTAS,0277,2004/11/02,NaN,NaN,NaN,NaN
8,ACTAS,0276,2004/10/21,NaN,NaN,NaN,NaN
9,ACTAS,0196,2004/10/12,NaN,NaN,NaN,NaN

In [3]:
df.tail(10)

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
26028,RESOLUCIONES,50939,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,FIJAR LOS DERECHOS DE MATRÍCULA Y COMPLEMENTAR...,NaN
26029,RESOLUCIONES,50949,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,TRASLADAR LA PLAZA NO 887 DEL DEPARTAMENTO DE ...,NaN
26030,RESOLUCIONES,50941,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,ACEPTAR LA RENUNCIA PRESENTADA POR LA SEÑORA N...,NaN
26031,RESOLUCIONES,50940,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,ACEPTAR LA RENUNCIA PRESENTADA POR EL SEÑOR HA...,NaN
26032,RESOLUCIONES,50944,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,COMISIONAR Y NOMBRAR AL SEÑOR JULIO EDUARDO HO...,NaN
26033,RESOLUCIONES,50948,2024/01/19,2024/01/19,NORMATIVA.UDEA.EDU.CO,ESTABLECER LINEAMIENTOS PARA LA IMPLEMENTACIÓN...,NaN
26034,RESOLUCIONES,50937,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,MODIFICAR EL ARTÍCULO 1 DE LA RESOLUCIÓN RECTO...,RESOLUCION RECTORAL 50835 DEL 27 DE NOVIEMBRE ...
26035,RESOLUCIONES,50936,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,CONCEDER COMISIÓN DE SERVICIOS A LA SEÑORA NAT...,NaN
26036,RESOLUCIONES,50938,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,CONCEDER COMISIÓN DE SERVICIOS AL SEÑOR GABRIE...,NaN
26037,RESOLUCIONES,50934,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,PRORROGAR LA COMISÓN ADMINISTRATIVA DE LA SEÑO...,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26038 entries, 0 to 26037
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tipo_documento       26038 non-null  str
 1   numero               26038 non-null  str
 2   fecha_expedicion     26038 non-null  str
 3   entrada_vigencia     1555 non-null   str
 4   medio_publicacion    21845 non-null  str
 5   resuelve             25065 non-null  str
 6   normas_relacionadas  2315 non-null   str
dtypes: str(7)
memory usage: 1.4 MB

In [5]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           0
entrada_vigencia       24483
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(1034)

In [7]:
antes = df['entrada_vigencia'].copy()
df['entrada_vigencia'] =pd.to_datetime(
    df['entrada_vigencia'],
    format='mixed',
    errors='coerce'
)

In [8]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           0
entrada_vigencia       24485
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64

In [9]:
cambiaron = antes.notna() & df['entrada_vigencia'].isna()

In [10]:
df.iloc[cambiaron]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
12753,RESOLUCIONES,2950,2015/09/28,NaT,NORMATIVA.UDEA.EDU.CO,AUTORIZAR LA CONVOCATORIA Y FIJAR REQUISITOS D...,NaN
20949,RESOLUCIONES,47233,2020/08/21,NaT,NORMATIVA.UDEA.EDU.CO,ESTABLECEN LOS LINEAMIENTOS PARA LA ENTREGA DE...,NaN

In [11]:
antes[cambiaron]

12753     2015/2016
20949    2020/28/21
Name: entrada_vigencia, dtype: str

In [12]:
df.loc[20949, 'entrada_vigencia'] = pd.to_datetime('2020/08/21')
df.loc[12753, 'entrada_vigencia'] = pd.to_datetime('2015/09/28')

In [13]:
df.loc[[12753,20949]]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
12753,RESOLUCIONES,2950,2015/09/28,2015-09-28,NORMATIVA.UDEA.EDU.CO,AUTORIZAR LA CONVOCATORIA Y FIJAR REQUISITOS D...,NaN
20949,RESOLUCIONES,47233,2020/08/21,2020-08-21,NORMATIVA.UDEA.EDU.CO,ESTABLECEN LOS LINEAMIENTOS PARA LA ENTREGA DE...,NaN

In [14]:
antes_expedicion = df['fecha_expedicion'].copy()
df['fecha_expedicion'] = pd.to_datetime(
    df['fecha_expedicion'],
    format='mixed',
    errors='coerce'
)

In [15]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           2
entrada_vigencia       24483
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64

In [16]:
cambiaron_expedicion = antes_expedicion.notna() & df['fecha_expedicion'].isna()

In [17]:
df.iloc[cambiaron_expedicion]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
803,ACTAS,624,NaT,NaT,NORMATIVA.UDEA.EDU.CO,NaN,NaN
15610,RESOLUCIONES,9619,NaT,NaT,NaN,CONCEDER DEDICACION EXCLUSIVA A ADRIANA MARIA ...,NaN

In [18]:
antes_expedicion[cambiaron_expedicion] # la 15610 es 2016/04/07 y la 803 es 2017/02/23

803      201702/23
15610    2016/04/0
Name: fecha_expedicion, dtype: str

In [19]:
df.loc[803, 'fecha_expedicion'] = pd.to_datetime('2017/02/23')
df.loc[15610, 'fecha_expedicion'] = pd.to_datetime('2016/04/07')

In [20]:
df.iloc[[803, 15610]]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
803,ACTAS,624,2017-02-23,NaT,NORMATIVA.UDEA.EDU.CO,NaN,NaN
15610,RESOLUCIONES,9619,2016-04-07,NaT,NaN,CONCEDER DEDICACION EXCLUSIVA A ADRIANA MARIA ...,NaN

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26038 entries, 0 to 26037
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tipo_documento       26038 non-null  str
 1   numero               26038 non-null  str
 2   fecha_expedicion     26038 non-null  datetime64[us]
 3   entrada_vigencia     1555 non-null   datetime64[us]
 4   medio_publicacion    21845 non-null  str
 5   resuelve             25065 non-null  str
 6   normas_relacionadas  2315 non-null   str
dtypes: datetime64[us](2), str(5)
memory usage: 1.4 MB

In [23]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           0
entrada_vigencia       24483
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64

In [28]:
df['entrada_vigencia'] = df['entrada_vigencia'].fillna('1900-01-01').apply(pd.to_datetime, errors='coerce')
df['medio_publicacion'] = df['medio_publicacion'].fillna('No registrado')
df['normas_relacionadas'] = df['normas_relacionadas'].fillna('No registradas')
df.dropna(subset=['resuelve'], inplace=True)

In [29]:
df.isnull().sum()

tipo_documento         0
numero                 0
fecha_expedicion       0
entrada_vigencia       0
medio_publicacion      0
resuelve               0
normas_relacionadas    0
dtype: int64

In [37]:
df.info()

<class 'pandas.DataFrame'>
Index: 25065 entries, 333 to 26037
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tipo_documento       25065 non-null  str
 1   numero               25065 non-null  str
 2   fecha_expedicion     25065 non-null  datetime64[us]
 3   entrada_vigencia     25065 non-null  datetime64[us]
 4   medio_publicacion    25065 non-null  str
 5   resuelve             25065 non-null  str
 6   normas_relacionadas  25065 non-null  str
dtypes: datetime64[us](2), str(5)
memory usage: 1.5 MB

In [30]:
df.duplicated().sum()

np.int64(1013)

In [32]:
df.loc[df.duplicated(keep=False)]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
1795,RESOLUCIONES,19968,2004-11-25,1900-01-01,NORMATIVA.UDEA.EDU.CO,ASIGNAR A MARGARITA MARIA RESTREPO GARAY JEFE ...,No registradas
1796,RESOLUCIONES,19964,2004-11-25,1900-01-01,NORMATIVA.UDEA.EDU.CO,PRORROGAR COMISION ADMINISTRATIVA A LUIS ALBER...,No registradas
1800,RESOLUCIONES,19968,2004-11-25,1900-01-01,NORMATIVA.UDEA.EDU.CO,ASIGNAR A MARGARITA MARIA RESTREPO GARAY JEFE ...,No registradas
1801,RESOLUCIONES,19964,2004-11-25,1900-01-01,NORMATIVA.UDEA.EDU.CO,PRORROGAR COMISION ADMINISTRATIVA A LUIS ALBER...,No registradas
1896,RESOLUCIONES,19800,2004-10-21,1900-01-01,NORMATIVA.UDEA.EDU.CO,COMISIONAR A URIEL LOZANO RIVEARA PROFESOR ESC...,RESOLUCION RECTORAL 19836 DEL 20 DE SEPTIEMBRE...
...,...,...,...,...,...,...,...
25770,RESOLUCIONES,51210,2024-05-02,1900-01-01,NORMATIVA.UDEA.EDU.CO,AUTORIZAR EL DUPLICADO DEL DIPLOMA DE GRADO A ...,No registradas
25809,RESOLUCIONES,51163,2024-04-10,1900-01-01,NORMATIVA.UDEA.EDU.CO,ACEPTAR LA RENUNCIA PRESENTADA POR EL SENOR CE...,No registradas
25810,RESOLUCIONES,51167,2024-04-10,1900-01-01,NORMATIVA.UDEA.EDU.CO,ASIGNAR RECURSOS EN LA VIGENCIA 2024 PROVENIEN...,No registradas
25812,RESOLUCIONES,51163,2024-04-10,1900-01-01,NORMATIVA.UDEA.EDU.CO,ACEPTAR LA RENUNCIA PRESENTADA POR EL SENOR CE...,No registradas
25813,RESOLUCIONES,51167,2024-04-10,1900-01-01,NORMATIVA.UDEA.EDU.CO,ASIGNAR RECURSOS EN LA VIGENCIA 2024 PROVENIEN...,No registradas

In [43]:
df.loc[[25810,25813]].T

,25810,25813
tipo_documento,RESOLUCIONES,RESOLUCIONES
numero,51167,51167
fecha_expedicion,2024-04-10 00:00:00,2024-04-10 00:00:00
entrada_vigencia,1900-01-01 00:00:00,1900-01-01 00:00:00
medio_publicacion,NORMATIVA.UDEA.EDU.CO,NORMATIVA.UDEA.EDU.CO
resuelve,ASIGNAR RECURSOS EN LA VIGENCIA 2024 PROVENIEN...,ASIGNAR RECURSOS EN LA VIGENCIA 2024 PROVENIEN...
normas_relacionadas,No registradas,No registradas

In [46]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [47]:
df.dtypes

tipo_documento                    str
numero                            str
fecha_expedicion       datetime64[us]
entrada_vigencia       datetime64[us]
medio_publicacion                 str
resuelve                          str
normas_relacionadas               str
dtype: object

In [ ]:
columnas_categoricas = ['tipo_documento', 'medio_publicacion', 'resuelve', 'normas_relacionadas']
for colu in columnas_categoricas:
    df[colu] = (
        df[colu]
        .str.strip() # elimina espacios al inicio y al final
        .str.lower() # pone todo en minúscula
        .str.replace(r"[^0-9a-z\s]+", " ", regex=True) #Elimina puntuación y simbolos
        .str.replace(r'\s+', ' ', regex=True) # Elimina espacios extra entre palabras
    )

In [52]:
df['resuelve_tokens'] = (
    df['resuelve']
    .str.split(" ")
    .apply(lambda toks: [t for t in toks if t])
)

In [53]:
df[['resuelve', 'resuelve_tokens']].head(5)

,resuelve,resuelve_tokens
333,aprobacion actas 619 y 620 informe vicerrector...,"[aprobacion, actas, 619, y, 620, informe, vice..."
338,aprobacion acta 618 informe vicerrectoria info...,"[aprobacion, acta, 618, informe, vicerrectoria..."
339,informe jurados convocatoria estrategia de sos...,"[informe, jurados, convocatoria, estrategia, d..."
341,aprobacion acta 616 informe vicerrectoria de i...,"[aprobacion, acta, 616, informe, vicerrectoria..."
344,balance de autoevaluacion en auditorio princip...,"[balance, de, autoevaluacion, en, auditorio, p..."

In [55]:
nltk.download('stopwords')

def eliminar_stopwords(df,col='resuelve_tokens', idioma='spanish', extras=None, conservar=None):
    stop = set(stopwords.words(idioma))
    if extras:
        stop |= set(extras)
    if conservar:
        stop -= set(conservar)
    def filtrar(toks):
        if toks is None:
            return []
        if isinstance(toks, str):
            toks = toks.split()
        if not isinstance(toks, list):
            return []
        return [t for t in toks if t and t not in stop]
    df[col] = df[col].apply(filtrar)
    return df
conservar = ['no']
eliminar_stopwords(
    df,
    col='resuelve_tokens',
    idioma='spanish',
    conservar=conservar
)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sebas\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas,resuelve_tokens
333,actas,621,2011-12-06,1900-01-01,no registrado,aprobacion actas 619 y 620 informe vicerrector...,no registradas,"[aprobacion, actas, 619, 620, informe, vicerre..."
338,actas,620,2011-11-22,1900-01-01,no registrado,aprobacion acta 618 informe vicerrectoria info...,no registradas,"[aprobacion, acta, 618, informe, vicerrectoria..."
339,actas,619,2011-11-17,1900-01-01,no registrado,informe jurados convocatoria estrategia de sos...,no registradas,"[informe, jurados, convocatoria, estrategia, s..."
341,actas,618,2011-11-08,1900-01-01,no registrado,aprobacion acta 616 informe vicerrectoria de i...,no registradas,"[aprobacion, acta, 616, informe, vicerrectoria..."
344,actas,617,2011-10-25,1900-01-01,no registrado,balance de autoevaluacion en auditorio princip...,no registradas,"[balance, autoevaluacion, auditorio, principal..."
...,...,...,...,...,...,...,...,...
26033,resoluciones,50948,2024-01-19,2024-01-19,normativa.udea.edu.co,establecer lineamientos para la implementación...,no registradas,"[establecer, lineamientos, implementación, con..."
26034,resoluciones,50937,2024-01-17,1900-01-01,normativa.udea.edu.co,modificar el artículo 1 de la resolución recto...,resolucion rectoral 50835 del 27 de noviembre ...,"[modificar, artículo, 1, resolución, rectoral,..."
26035,resoluciones,50936,2024-01-17,1900-01-01,normativa.udea.edu.co,conceder comisión de servicios a la señora nat...,no registradas,"[conceder, comisión, servicios, señora, natali..."
26036,resoluciones,50938,2024-01-17,1900-01-01,normativa.udea.edu.co,conceder comisión de servicios al señor gabrie...,no registradas,"[conceder, comisión, servicios, señor, gabriel..."
26037,resoluciones,50934,2024-01-17,1900-01-01,normativa.udea.edu.co,prorrogar la comisón administrativa de la seño...,no registradas,"[prorrogar, comisón, administrativa, señora, a..."

In [56]:
df[['resuelve_tokens']].head(5)

                                       resuelve_tokens
333  [aprobacion, actas, 619, 620, informe, vicerre...
338  [aprobacion, acta, 618, informe, vicerrectoria...
339  [informe, jurados, convocatoria, estrategia, s...
341  [aprobacion, acta, 616, informe, vicerrectoria...
344  [balance, autoevaluacion, auditorio, principal...