In [1]:
import pandas as pd
import matplotlib.pyplot

In [2]:
datos = "documentos_udea_2004_2024.xlsx"
df = pd.read_excel(datos)
df.head(10)

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
0,ACTAS,0198,2004/12/14,NaN,NaN,NaN,NaN
1,ACTAS,0283,2004/12/09,NaN,NaN,NaN,NaN
2,ACTAS,0282,2004/12/02,NaN,NaN,NaN,NaN
3,ACTAS,0280,2004/11/18,NaN,NaN,NaN,NaN
4,ACTAS,0279,2004/11/11,NaN,NaN,NaN,NaN
5,ACTAS,0197,2004/11/09,NaN,NaN,NaN,NaN
6,ACTAS,0278,2004/11/04,NaN,NaN,NaN,NaN
7,ACTAS,0277,2004/11/02,NaN,NaN,NaN,NaN
8,ACTAS,0276,2004/10/21,NaN,NaN,NaN,NaN
9,ACTAS,0196,2004/10/12,NaN,NaN,NaN,NaN

In [3]:
df.tail(10)

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
26028,RESOLUCIONES,50939,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,FIJAR LOS DERECHOS DE MATRÍCULA Y COMPLEMENTAR...,NaN
26029,RESOLUCIONES,50949,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,TRASLADAR LA PLAZA NO 887 DEL DEPARTAMENTO DE ...,NaN
26030,RESOLUCIONES,50941,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,ACEPTAR LA RENUNCIA PRESENTADA POR LA SEÑORA N...,NaN
26031,RESOLUCIONES,50940,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,ACEPTAR LA RENUNCIA PRESENTADA POR EL SEÑOR HA...,NaN
26032,RESOLUCIONES,50944,2024/01/19,NaN,NORMATIVA.UDEA.EDU.CO,COMISIONAR Y NOMBRAR AL SEÑOR JULIO EDUARDO HO...,NaN
26033,RESOLUCIONES,50948,2024/01/19,2024/01/19,NORMATIVA.UDEA.EDU.CO,ESTABLECER LINEAMIENTOS PARA LA IMPLEMENTACIÓN...,NaN
26034,RESOLUCIONES,50937,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,MODIFICAR EL ARTÍCULO 1 DE LA RESOLUCIÓN RECTO...,RESOLUCION RECTORAL 50835 DEL 27 DE NOVIEMBRE ...
26035,RESOLUCIONES,50936,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,CONCEDER COMISIÓN DE SERVICIOS A LA SEÑORA NAT...,NaN
26036,RESOLUCIONES,50938,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,CONCEDER COMISIÓN DE SERVICIOS AL SEÑOR GABRIE...,NaN
26037,RESOLUCIONES,50934,2024/01/17,NaN,NORMATIVA.UDEA.EDU.CO,PRORROGAR LA COMISÓN ADMINISTRATIVA DE LA SEÑO...,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26038 entries, 0 to 26037
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tipo_documento       26038 non-null  str
 1   numero               26038 non-null  str
 2   fecha_expedicion     26038 non-null  str
 3   entrada_vigencia     1555 non-null   str
 4   medio_publicacion    21845 non-null  str
 5   resuelve             25065 non-null  str
 6   normas_relacionadas  2315 non-null   str
dtypes: str(7)
memory usage: 1.4 MB

In [5]:
df.isnull().sum()

tipo_documento             0
numero                     0
fecha_expedicion           0
entrada_vigencia       24483
medio_publicacion       4193
resuelve                 973
normas_relacionadas    23723
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(1034)

In [13]:
antes = df['entrada_vigencia'].copy()
df['entrada_vigencia'] =pd.to_datetime(df['entrada_vigencia'], errors='coerce')

In [14]:
cambiaron = antes.notna() & df['entrada_vigencia'].isna()

In [15]:
df.loc[cambiaron, 'entrada_vigencia']

12753   NaT
20394   NaT
20949   NaT
Name: entrada_vigencia, dtype: datetime64[us]

In [19]:
df.iloc[cambiaron]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
12753,RESOLUCIONES,2950,2015/09/28,NaT,NORMATIVA.UDEA.EDU.CO,AUTORIZAR LA CONVOCATORIA Y FIJAR REQUISITOS D...,NaN
20394,RESOLUCIONES,45390,2019/02/19,NaT,NORMATIVA.UDEA.EDU.CO,TRASLADAR LOS RECURSOS ASIGNADOS AL PROYECTO E...,RESOLUCION RECTORAL 40714 DEL 23 DE SEPTIEMBRE...
20949,RESOLUCIONES,47233,2020/08/21,NaT,NORMATIVA.UDEA.EDU.CO,ESTABLECEN LOS LINEAMIENTOS PARA LA ENTREGA DE...,NaN

In [16]:
antes[cambiaron]

12753     2015/2016
20394    19/02/2019
20949    2020/28/21
Name: entrada_vigencia, dtype: str

In [23]:
antes_expedicion = df['fecha_expedicion'].copy()
df['fecha_expedicion'] = pd.to_datetime(df['fecha_expedicion'], errors='coerce')

In [24]:
cambiaron_expedicion = antes_expedicion.notna() & df['fecha_expedicion'].isna()

In [27]:
df.iloc[cambiaron_expedicion]

,tipo_documento,numero,fecha_expedicion,entrada_vigencia,medio_publicacion,resuelve,normas_relacionadas
803,ACTAS,624,NaT,NaT,NORMATIVA.UDEA.EDU.CO,NaN,NaN
2774,RESOLUCIONES,19374,NaT,NaT,NORMATIVA.UDEA.EDU.CO,PRORROGAR COMISION ADMINISTRATIVA A LUIS ALBER...,NaN
2775,RESOLUCIONES,19372,NaT,NaT,NORMATIVA.UDEA.EDU.CO,DAR POR TERMINADA COMISION ADMINISTRATIVA A MA...,NaN
2776,RESOLUCIONES,19136,NaT,NaT,NORMATIVA.UDEA.EDU.CO,DAR POR TERMINADA COMISION ADMINISTRATIVA A JU...,NaN
2777,RESOLUCIONES,19128,NaT,NaT,NORMATIVA.UDEA.EDU.CO,NOMBRAR A MARIA EUGENIA RODRIGUEZ GOMEZ COMO P...,NaN
2778,RESOLUCIONES,19133,NaT,NaT,NORMATIVA.UDEA.EDU.CO,MODIFICAR NOMBRAMIENTO A JHON JAIRO TIRADO QUI...,RESOLUCION RECTORAL 19006 DEL 18 DE JUNIO DE 2004
2779,RESOLUCIONES,19130,NaT,NaT,NORMATIVA.UDEA.EDU.CO,NOMBRAR A IVAN DARIO URIBE PAREJA COMO DIRECTO...,NaN
2780,RESOLUCIONES,19131,NaT,NaT,NORMATIVA.UDEA.EDU.CO,DESIGNAR A MARIA EUGENIA ECHEVERRI RESTREPO CO...,NaN
2781,RESOLUCIONES,19134,NaT,NaT,NORMATIVA.UDEA.EDU.CO,ACOGER RECOMENDACIONES DEL COMITE DE DESARROLL...,NaN
2782,RESOLUCIONES,19134,NaT,NaT,NORMATIVA.UDEA.EDU.CO,COMISIONAR A JHON RAMIRO AGUDELO SANTAMARIA PR...,NaN
2783,RESOLUCIONES,19123,NaT,NaT,NORMATIVA.UDEA.EDU.CO,DESIGNAR A AZAEL CARVAJAL MARTINEZ Y CARLOS FE...,NaN
2784,RESOLUCIONES,19126,NaT,NaT,NORMATIVA.UDEA.EDU.CO,PRORROGAR NOMBRAMIENTO A BEATRIZ ELENA AGUDELO...,NaN
2785,RESOLUCIONES,19125,NaT,NaT,NORMATIVA.UDEA.EDU.CO,NOMBRAR A MAURICIO VASQUEZ GOMEZ COMO VICEDECA...,NaN
2786,RESOLUCIONES,19124,NaT,NaT,NORMATIVA.UDEA.EDU.CO,VENDER UN COMPUTADOR EN DESUSO AL CENTRO EDUCA...,NaN
2787,RESOLUCIONES,19120,NaT,NaT,NORMATIVA.UDEA.EDU.CO,AUTORIZAR PAGO A LA UNIVERSIDAD SERGIO ARBOLEDA,NaN
2788,RESOLUCIONES,19121,NaT,NaT,NORMATIVA.UDEA.EDU.CO,DELEGAR ORDENACION DE GASTOS UNIDADES EJECUTOR...,NaN
2789,RESOLUCIONES,19119,NaT,NaT,NORMATIVA.UDEA.EDU.CO,COMISIONAR A NICOLAS CARLOS MARTIN DE JESUS JA...,NaN
2790,RESOLUCIONES,19118,NaT,NaT,NORMATIVA.UDEA.EDU.CO,CONCEDER COMISION DE SERVICIOS A MARIA ADELAID...,NaN
2791,RESOLUCIONES,19116,NaT,NaT,NORMATIVA.UDEA.EDU.CO,CONVOCAR POR TERCERA VEZ A ELECCION DEL REPRES...,NaN
2792,RESOLUCIONES,19101,NaT,NaT,NORMATIVA.UDEA.EDU.CO,PRORROGAR COMISION ADMINISTRATIVA A YOMAIRA VI...,NaN
2793,RESOLUCIONES,19105,NaT,NaT,NORMATIVA.UDEA.EDU.CO,PRORROGAR NOMBRAMIENTO A JENNY ANDREA MIRA ESP...,NaN
2794,RESOLUCIONES,19106,NaT,NaT,NORMATIVA.UDEA.EDU.CO,MODIFICAR EL ARTICULO 1 RESOLUCION RECTORAL 16...,RESOLUCION RECTORAL 16620 DEL 1 DE OCTUBRE DE ...
2795,RESOLUCIONES,19109,NaT,NaT,NORMATIVA.UDEA.EDU.CO,PRORROGAR COMISION ADMINISTRATIVA A JORGE FARB...,NaN
2796,RESOLUCIONES,19108,NaT,NaT,NORMATIVA.UDEA.EDU.CO,COMISIONAR A FABIO VELEZ MACIAS Y ELKIN LIBARD...,NaN
2797,RESOLUCIONES,19104,NaT,NaT,NORMATIVA.UDEA.EDU.CO,CREAR LA UNIDAD EJECUTORA 9781 CONVENIO MUNICI...,NaN
2798,RESOLUCIONES,19103,NaT,NaT,NORMATIVA.UDEA.EDU.CO,EXTENDER VIGENCIA DE RESOLUCION RECTORAL 15949...,RESOLUCION RECTORAL 15949 DEL 22 DE MAYO DE 2002
15610,RESOLUCIONES,9619,NaT,NaT,NaN,CONCEDER DEDICACION EXCLUSIVA A ADRIANA MARIA ...,NaN

In [25]:
antes_expedicion[cambiaron_expedicion]

803       201702/23
2774     2004/ 7/29
2775     2004/ 7/26
2776     2004/ 6/22
2777     2004/ 6/18
2778     2004/ 6/18
2779     2004/ 6/18
2780     2004/ 6/18
2781     2004/ 6/18
2782     2004/ 6/18
2783     2004/ 6/16
2784     2004/ 6/16
2785     2004/ 6/16
2786     2004/ 6/16
2787     2004/ 6/16
2788     2004/ 6/16
2789     2004/ 6/16
2790     2004/ 6/16
2791     2004/ 6/15
2792     2004/ 6/11
2793     2004/ 6/11
2794     2004/ 6/11
2795     2004/ 6/11
2796     2004/ 6/11
2797     2004/ 6/11
2798     2004/ 6/10
15610     2016/04/0
Name: fecha_expedicion, dtype: str

In [30]:
df.iloc[15610]

tipo_documento                                              RESOLUCIONES
numero                                                              9619
fecha_expedicion                                                     NaT
entrada_vigencia                                                     NaT
medio_publicacion                                                    NaN
resuelve               CONCEDER DEDICACION EXCLUSIVA A ADRIANA MARIA ...
normas_relacionadas                                                  NaN
Name: 15610, dtype: object

In [7]:
#df['fecha_expedicion'] = pd.to_datetime(df['fecha_expedicion'], errors='coerce')
#df['entrada_vigencia'] = pd.to_datetime(df['entrada_vigencia'], errors='coerce')

In [8]:
#df.head(10)

In [9]:
#df.info()

In [10]:
#df.isnull().sum()

In [11]:
#df.loc[df['fecha_expedicion'].isnull()]

In [12]:
#df.iloc[803]